//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawrukmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string FlickrImageUrl { get; set; }
        public Nullable<int> Visibility { get; set; }
    }
}
