//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawrukmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEntry
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Url { get; set; }
        public int Type { get; set; }
        public Nullable<int> Visibility { get; set; }
    }
}
