//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawrukmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamousDeveloper
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Summary { get; set; }
        public string StackOverflowUrl { get; set; }
        public string WikipediaUrl { get; set; }
        public string Websites { get; set; }
        public string Books { get; set; }
        public string TwitterUrl { get; set; }
        public string FacebookUrl { get; set; }
        public string PhotoUrl { get; set; }
        public string PrimaryLanguage { get; set; }
        public string Nickname { get; set; }
    }
}
