//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawrukmvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BlogPost> BlogPosts { get; set; }
        public DbSet<BlogPostTag> BlogPostTags { get; set; }
        public DbSet<CalendarEntry> CalendarEntries { get; set; }
        public DbSet<FamousDeveloper> FamousDevelopers { get; set; }
        public DbSet<OlympicResult> OlympicResults { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<RaceResult> RaceResults { get; set; }
        public DbSet<Route> Routes { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<VideoTag> VideoTags { get; set; }
    }
}
