//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("lawrukmvc.Models", "VideoTag1", "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(lawrukmvc.Tag), "Video", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(lawrukmvc.Video))]

#endregion

namespace lawrukmvc
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class lawrukEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new lawrukEntities object using the connection string found in the 'lawrukEntities' section of the application configuration file.
        /// </summary>
        public lawrukEntities() : base("name=lawrukEntities", "lawrukEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new lawrukEntities object.
        /// </summary>
        public lawrukEntities(string connectionString) : base(connectionString, "lawrukEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new lawrukEntities object.
        /// </summary>
        public lawrukEntities(EntityConnection connection) : base(connection, "lawrukEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogPost> BlogPosts
        {
            get
            {
                if ((_BlogPosts == null))
                {
                    _BlogPosts = base.CreateObjectSet<BlogPost>("BlogPosts");
                }
                return _BlogPosts;
            }
        }
        private ObjectSet<BlogPost> _BlogPosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogPostTag> BlogPostTags
        {
            get
            {
                if ((_BlogPostTags == null))
                {
                    _BlogPostTags = base.CreateObjectSet<BlogPostTag>("BlogPostTags");
                }
                return _BlogPostTags;
            }
        }
        private ObjectSet<BlogPostTag> _BlogPostTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CalendarEntry> CalendarEntries
        {
            get
            {
                if ((_CalendarEntries == null))
                {
                    _CalendarEntries = base.CreateObjectSet<CalendarEntry>("CalendarEntries");
                }
                return _CalendarEntries;
            }
        }
        private ObjectSet<CalendarEntry> _CalendarEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FamousDeveloper> FamousDevelopers
        {
            get
            {
                if ((_FamousDevelopers == null))
                {
                    _FamousDevelopers = base.CreateObjectSet<FamousDeveloper>("FamousDevelopers");
                }
                return _FamousDevelopers;
            }
        }
        private ObjectSet<FamousDeveloper> _FamousDevelopers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OlympicResult> OlympicResults
        {
            get
            {
                if ((_OlympicResults == null))
                {
                    _OlympicResults = base.CreateObjectSet<OlympicResult>("OlympicResults");
                }
                return _OlympicResults;
            }
        }
        private ObjectSet<OlympicResult> _OlympicResults;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RaceResult> RaceResults
        {
            get
            {
                if ((_RaceResults == null))
                {
                    _RaceResults = base.CreateObjectSet<RaceResult>("RaceResults");
                }
                return _RaceResults;
            }
        }
        private ObjectSet<RaceResult> _RaceResults;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Video> Videos
        {
            get
            {
                if ((_Videos == null))
                {
                    _Videos = base.CreateObjectSet<Video>("Videos");
                }
                return _Videos;
            }
        }
        private ObjectSet<Video> _Videos;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogPosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogPosts(BlogPost blogPost)
        {
            base.AddObject("BlogPosts", blogPost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogPostTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogPostTags(BlogPostTag blogPostTag)
        {
            base.AddObject("BlogPostTags", blogPostTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CalendarEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalendarEntries(CalendarEntry calendarEntry)
        {
            base.AddObject("CalendarEntries", calendarEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FamousDevelopers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFamousDevelopers(FamousDeveloper famousDeveloper)
        {
            base.AddObject("FamousDevelopers", famousDeveloper);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OlympicResults EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOlympicResults(OlympicResult olympicResult)
        {
            base.AddObject("OlympicResults", olympicResult);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RaceResults EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRaceResults(RaceResult raceResult)
        {
            base.AddObject("RaceResults", raceResult);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Videos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideos(Video video)
        {
            base.AddObject("Videos", video);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="BlogPost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogPost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogPost object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="flickrImageUrl">Initial value of the FlickrImageUrl property.</param>
        public static BlogPost CreateBlogPost(global::System.Int32 id, global::System.DateTime date, global::System.DateTime lastModified, global::System.String title, global::System.String body, global::System.String flickrImageUrl)
        {
            BlogPost blogPost = new BlogPost();
            blogPost.Id = id;
            blogPost.Date = date;
            blogPost.LastModified = lastModified;
            blogPost.Title = title;
            blogPost.Body = body;
            blogPost.FlickrImageUrl = flickrImageUrl;
            return blogPost;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value, "LastModified");
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false, "Body");
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FlickrImageUrl
        {
            get
            {
                return _FlickrImageUrl;
            }
            set
            {
                OnFlickrImageUrlChanging(value);
                ReportPropertyChanging("FlickrImageUrl");
                _FlickrImageUrl = StructuralObject.SetValidValue(value, false, "FlickrImageUrl");
                ReportPropertyChanged("FlickrImageUrl");
                OnFlickrImageUrlChanged();
            }
        }
        private global::System.String _FlickrImageUrl;
        partial void OnFlickrImageUrlChanging(global::System.String value);
        partial void OnFlickrImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Visibility
        {
            get
            {
                return _Visibility;
            }
            set
            {
                OnVisibilityChanging(value);
                ReportPropertyChanging("Visibility");
                _Visibility = StructuralObject.SetValidValue(value, "Visibility");
                ReportPropertyChanged("Visibility");
                OnVisibilityChanged();
            }
        }
        private Nullable<global::System.Int32> _Visibility;
        partial void OnVisibilityChanging(Nullable<global::System.Int32> value);
        partial void OnVisibilityChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="BlogPostTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogPostTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogPostTag object.
        /// </summary>
        /// <param name="blogPostId">Initial value of the BlogPostId property.</param>
        /// <param name="tagId">Initial value of the TagId property.</param>
        public static BlogPostTag CreateBlogPostTag(global::System.Int32 blogPostId, global::System.Int32 tagId)
        {
            BlogPostTag blogPostTag = new BlogPostTag();
            blogPostTag.BlogPostId = blogPostId;
            blogPostTag.TagId = tagId;
            return blogPostTag;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogPostId
        {
            get
            {
                return _BlogPostId;
            }
            set
            {
                if (_BlogPostId != value)
                {
                    OnBlogPostIdChanging(value);
                    ReportPropertyChanging("BlogPostId");
                    _BlogPostId = StructuralObject.SetValidValue(value, "BlogPostId");
                    ReportPropertyChanged("BlogPostId");
                    OnBlogPostIdChanged();
                }
            }
        }
        private global::System.Int32 _BlogPostId;
        partial void OnBlogPostIdChanging(global::System.Int32 value);
        partial void OnBlogPostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagId
        {
            get
            {
                return _TagId;
            }
            set
            {
                if (_TagId != value)
                {
                    OnTagIdChanging(value);
                    ReportPropertyChanging("TagId");
                    _TagId = StructuralObject.SetValidValue(value, "TagId");
                    ReportPropertyChanged("TagId");
                    OnTagIdChanged();
                }
            }
        }
        private global::System.Int32 _TagId;
        partial void OnTagIdChanging(global::System.Int32 value);
        partial void OnTagIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="CalendarEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CalendarEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CalendarEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static CalendarEntry CreateCalendarEntry(global::System.Int32 id, global::System.String title, global::System.DateTime date, global::System.String url, global::System.Int32 type)
        {
            CalendarEntry calendarEntry = new CalendarEntry();
            calendarEntry.Id = id;
            calendarEntry.Title = title;
            calendarEntry.Date = date;
            calendarEntry.Url = url;
            calendarEntry.Type = type;
            return calendarEntry;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Visibility
        {
            get
            {
                return _Visibility;
            }
            set
            {
                OnVisibilityChanging(value);
                ReportPropertyChanging("Visibility");
                _Visibility = StructuralObject.SetValidValue(value, "Visibility");
                ReportPropertyChanged("Visibility");
                OnVisibilityChanged();
            }
        }
        private Nullable<global::System.Int32> _Visibility;
        partial void OnVisibilityChanging(Nullable<global::System.Int32> value);
        partial void OnVisibilityChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="FamousDeveloper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FamousDeveloper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FamousDeveloper object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="middleName">Initial value of the MiddleName property.</param>
        /// <param name="summary">Initial value of the Summary property.</param>
        /// <param name="stackOverflowUrl">Initial value of the StackOverflowUrl property.</param>
        /// <param name="wikipediaUrl">Initial value of the WikipediaUrl property.</param>
        /// <param name="websites">Initial value of the Websites property.</param>
        /// <param name="books">Initial value of the Books property.</param>
        /// <param name="twitterUrl">Initial value of the TwitterUrl property.</param>
        /// <param name="facebookUrl">Initial value of the FacebookUrl property.</param>
        /// <param name="photoUrl">Initial value of the PhotoUrl property.</param>
        /// <param name="primaryLanguage">Initial value of the PrimaryLanguage property.</param>
        /// <param name="nickname">Initial value of the Nickname property.</param>
        public static FamousDeveloper CreateFamousDeveloper(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.String middleName, global::System.String summary, global::System.String stackOverflowUrl, global::System.String wikipediaUrl, global::System.String websites, global::System.String books, global::System.String twitterUrl, global::System.String facebookUrl, global::System.String photoUrl, global::System.String primaryLanguage, global::System.String nickname)
        {
            FamousDeveloper famousDeveloper = new FamousDeveloper();
            famousDeveloper.Id = id;
            famousDeveloper.FirstName = firstName;
            famousDeveloper.LastName = lastName;
            famousDeveloper.MiddleName = middleName;
            famousDeveloper.Summary = summary;
            famousDeveloper.StackOverflowUrl = stackOverflowUrl;
            famousDeveloper.WikipediaUrl = wikipediaUrl;
            famousDeveloper.Websites = websites;
            famousDeveloper.Books = books;
            famousDeveloper.TwitterUrl = twitterUrl;
            famousDeveloper.FacebookUrl = facebookUrl;
            famousDeveloper.PhotoUrl = photoUrl;
            famousDeveloper.PrimaryLanguage = primaryLanguage;
            famousDeveloper.Nickname = nickname;
            return famousDeveloper;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, false, "MiddleName");
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, false, "Summary");
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StackOverflowUrl
        {
            get
            {
                return _StackOverflowUrl;
            }
            set
            {
                OnStackOverflowUrlChanging(value);
                ReportPropertyChanging("StackOverflowUrl");
                _StackOverflowUrl = StructuralObject.SetValidValue(value, false, "StackOverflowUrl");
                ReportPropertyChanged("StackOverflowUrl");
                OnStackOverflowUrlChanged();
            }
        }
        private global::System.String _StackOverflowUrl;
        partial void OnStackOverflowUrlChanging(global::System.String value);
        partial void OnStackOverflowUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WikipediaUrl
        {
            get
            {
                return _WikipediaUrl;
            }
            set
            {
                OnWikipediaUrlChanging(value);
                ReportPropertyChanging("WikipediaUrl");
                _WikipediaUrl = StructuralObject.SetValidValue(value, false, "WikipediaUrl");
                ReportPropertyChanged("WikipediaUrl");
                OnWikipediaUrlChanged();
            }
        }
        private global::System.String _WikipediaUrl;
        partial void OnWikipediaUrlChanging(global::System.String value);
        partial void OnWikipediaUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Websites
        {
            get
            {
                return _Websites;
            }
            set
            {
                OnWebsitesChanging(value);
                ReportPropertyChanging("Websites");
                _Websites = StructuralObject.SetValidValue(value, false, "Websites");
                ReportPropertyChanged("Websites");
                OnWebsitesChanged();
            }
        }
        private global::System.String _Websites;
        partial void OnWebsitesChanging(global::System.String value);
        partial void OnWebsitesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Books
        {
            get
            {
                return _Books;
            }
            set
            {
                OnBooksChanging(value);
                ReportPropertyChanging("Books");
                _Books = StructuralObject.SetValidValue(value, false, "Books");
                ReportPropertyChanged("Books");
                OnBooksChanged();
            }
        }
        private global::System.String _Books;
        partial void OnBooksChanging(global::System.String value);
        partial void OnBooksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TwitterUrl
        {
            get
            {
                return _TwitterUrl;
            }
            set
            {
                OnTwitterUrlChanging(value);
                ReportPropertyChanging("TwitterUrl");
                _TwitterUrl = StructuralObject.SetValidValue(value, false, "TwitterUrl");
                ReportPropertyChanged("TwitterUrl");
                OnTwitterUrlChanged();
            }
        }
        private global::System.String _TwitterUrl;
        partial void OnTwitterUrlChanging(global::System.String value);
        partial void OnTwitterUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FacebookUrl
        {
            get
            {
                return _FacebookUrl;
            }
            set
            {
                OnFacebookUrlChanging(value);
                ReportPropertyChanging("FacebookUrl");
                _FacebookUrl = StructuralObject.SetValidValue(value, false, "FacebookUrl");
                ReportPropertyChanged("FacebookUrl");
                OnFacebookUrlChanged();
            }
        }
        private global::System.String _FacebookUrl;
        partial void OnFacebookUrlChanging(global::System.String value);
        partial void OnFacebookUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhotoUrl
        {
            get
            {
                return _PhotoUrl;
            }
            set
            {
                OnPhotoUrlChanging(value);
                ReportPropertyChanging("PhotoUrl");
                _PhotoUrl = StructuralObject.SetValidValue(value, false, "PhotoUrl");
                ReportPropertyChanged("PhotoUrl");
                OnPhotoUrlChanged();
            }
        }
        private global::System.String _PhotoUrl;
        partial void OnPhotoUrlChanging(global::System.String value);
        partial void OnPhotoUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryLanguage
        {
            get
            {
                return _PrimaryLanguage;
            }
            set
            {
                OnPrimaryLanguageChanging(value);
                ReportPropertyChanging("PrimaryLanguage");
                _PrimaryLanguage = StructuralObject.SetValidValue(value, false, "PrimaryLanguage");
                ReportPropertyChanged("PrimaryLanguage");
                OnPrimaryLanguageChanged();
            }
        }
        private global::System.String _PrimaryLanguage;
        partial void OnPrimaryLanguageChanging(global::System.String value);
        partial void OnPrimaryLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nickname
        {
            get
            {
                return _Nickname;
            }
            set
            {
                OnNicknameChanging(value);
                ReportPropertyChanging("Nickname");
                _Nickname = StructuralObject.SetValidValue(value, false, "Nickname");
                ReportPropertyChanged("Nickname");
                OnNicknameChanged();
            }
        }
        private global::System.String _Nickname;
        partial void OnNicknameChanging(global::System.String value);
        partial void OnNicknameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="OlympicResult")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OlympicResult : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OlympicResult object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="place">Initial value of the Place property.</param>
        /// <param name="event">Initial value of the Event property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        public static OlympicResult CreateOlympicResult(global::System.Int32 id, global::System.Int32 place, global::System.String @event, global::System.Int32 year, global::System.String city, global::System.String firstName, global::System.String lastName, global::System.String time, global::System.String gender)
        {
            OlympicResult olympicResult = new OlympicResult();
            olympicResult.Id = id;
            olympicResult.Place = place;
            olympicResult.Event = @event;
            olympicResult.Year = year;
            olympicResult.City = city;
            olympicResult.FirstName = firstName;
            olympicResult.LastName = lastName;
            olympicResult.Time = time;
            olympicResult.Gender = gender;
            return olympicResult;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Place
        {
            get
            {
                return _Place;
            }
            set
            {
                OnPlaceChanging(value);
                ReportPropertyChanging("Place");
                _Place = StructuralObject.SetValidValue(value, "Place");
                ReportPropertyChanged("Place");
                OnPlaceChanged();
            }
        }
        private global::System.Int32 _Place;
        partial void OnPlaceChanging(global::System.Int32 value);
        partial void OnPlaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Event
        {
            get
            {
                return _Event;
            }
            set
            {
                OnEventChanging(value);
                ReportPropertyChanging("Event");
                _Event = StructuralObject.SetValidValue(value, false, "Event");
                ReportPropertyChanged("Event");
                OnEventChanged();
            }
        }
        private global::System.String _Event;
        partial void OnEventChanging(global::System.String value);
        partial void OnEventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, "Year");
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false, "Time");
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Person CreatePerson(global::System.Int32 id)
        {
            Person person = new Person();
            person.Id = id;
            return person;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true, "MiddleName");
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BirthdayYear
        {
            get
            {
                return _BirthdayYear;
            }
            set
            {
                OnBirthdayYearChanging(value);
                ReportPropertyChanging("BirthdayYear");
                _BirthdayYear = StructuralObject.SetValidValue(value, "BirthdayYear");
                ReportPropertyChanged("BirthdayYear");
                OnBirthdayYearChanged();
            }
        }
        private Nullable<global::System.Int32> _BirthdayYear;
        partial void OnBirthdayYearChanging(Nullable<global::System.Int32> value);
        partial void OnBirthdayYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BirthdayMonth
        {
            get
            {
                return _BirthdayMonth;
            }
            set
            {
                OnBirthdayMonthChanging(value);
                ReportPropertyChanging("BirthdayMonth");
                _BirthdayMonth = StructuralObject.SetValidValue(value, "BirthdayMonth");
                ReportPropertyChanged("BirthdayMonth");
                OnBirthdayMonthChanged();
            }
        }
        private Nullable<global::System.Int32> _BirthdayMonth;
        partial void OnBirthdayMonthChanging(Nullable<global::System.Int32> value);
        partial void OnBirthdayMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BirthdayDay
        {
            get
            {
                return _BirthdayDay;
            }
            set
            {
                OnBirthdayDayChanging(value);
                ReportPropertyChanging("BirthdayDay");
                _BirthdayDay = StructuralObject.SetValidValue(value, "BirthdayDay");
                ReportPropertyChanged("BirthdayDay");
                OnBirthdayDayChanged();
            }
        }
        private Nullable<global::System.Int32> _BirthdayDay;
        partial void OnBirthdayDayChanging(Nullable<global::System.Int32> value);
        partial void OnBirthdayDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true, "Address");
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true, "State");
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true, "Zip");
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CellPhone
        {
            get
            {
                return _CellPhone;
            }
            set
            {
                OnCellPhoneChanging(value);
                ReportPropertyChanging("CellPhone");
                _CellPhone = StructuralObject.SetValidValue(value, "CellPhone");
                ReportPropertyChanged("CellPhone");
                OnCellPhoneChanged();
            }
        }
        private Nullable<global::System.Int64> _CellPhone;
        partial void OnCellPhoneChanging(Nullable<global::System.Int64> value);
        partial void OnCellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GoogleId
        {
            get
            {
                return _GoogleId;
            }
            set
            {
                OnGoogleIdChanging(value);
                ReportPropertyChanging("GoogleId");
                _GoogleId = StructuralObject.SetValidValue(value, true, "GoogleId");
                ReportPropertyChanged("GoogleId");
                OnGoogleIdChanged();
            }
        }
        private global::System.String _GoogleId;
        partial void OnGoogleIdChanging(global::System.String value);
        partial void OnGoogleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YahooId
        {
            get
            {
                return _YahooId;
            }
            set
            {
                OnYahooIdChanging(value);
                ReportPropertyChanging("YahooId");
                _YahooId = StructuralObject.SetValidValue(value, true, "YahooId");
                ReportPropertyChanged("YahooId");
                OnYahooIdChanged();
            }
        }
        private global::System.String _YahooId;
        partial void OnYahooIdChanging(global::System.String value);
        partial void OnYahooIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="RaceResult")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RaceResult : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RaceResult object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="distance">Initial value of the Distance property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="seconds">Initial value of the Seconds property.</param>
        public static RaceResult CreateRaceResult(global::System.Int32 id, global::System.String title, global::System.String distance, global::System.String url, global::System.String city, global::System.String state, global::System.DateTime date, global::System.Int32 seconds)
        {
            RaceResult raceResult = new RaceResult();
            raceResult.Id = id;
            raceResult.Title = title;
            raceResult.Distance = distance;
            raceResult.Url = url;
            raceResult.City = city;
            raceResult.State = state;
            raceResult.Date = date;
            raceResult.Seconds = seconds;
            return raceResult;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Distance
        {
            get
            {
                return _Distance;
            }
            set
            {
                OnDistanceChanging(value);
                ReportPropertyChanging("Distance");
                _Distance = StructuralObject.SetValidValue(value, false, "Distance");
                ReportPropertyChanged("Distance");
                OnDistanceChanged();
            }
        }
        private global::System.String _Distance;
        partial void OnDistanceChanging(global::System.String value);
        partial void OnDistanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false, "State");
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seconds
        {
            get
            {
                return _Seconds;
            }
            set
            {
                OnSecondsChanging(value);
                ReportPropertyChanging("Seconds");
                _Seconds = StructuralObject.SetValidValue(value, "Seconds");
                ReportPropertyChanged("Seconds");
                OnSecondsChanged();
            }
        }
        private global::System.Int32 _Seconds;
        partial void OnSecondsChanging(global::System.Int32 value);
        partial void OnSecondsChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static Tag CreateTag(global::System.Int32 id, global::System.String title)
        {
            Tag tag = new Tag();
            tag.Id = id;
            tag.Title = title;
            return tag;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lawrukmvc.Models", "VideoTag1", "Video")]
        public EntityCollection<Video> Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Video>("lawrukmvc.Models.VideoTag1", "Video");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Video>("lawrukmvc.Models.VideoTag1", "Video", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lawrukmvc.Models", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="youTubeId">Initial value of the YouTubeId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Video CreateVideo(global::System.Int32 id, global::System.String title, global::System.String youTubeId, global::System.DateTime date)
        {
            Video video = new Video();
            video.Id = id;
            video.Title = title;
            video.YouTubeId = youTubeId;
            video.Date = date;
            return video;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YouTubeId
        {
            get
            {
                return _YouTubeId;
            }
            set
            {
                OnYouTubeIdChanging(value);
                ReportPropertyChanging("YouTubeId");
                _YouTubeId = StructuralObject.SetValidValue(value, false, "YouTubeId");
                ReportPropertyChanged("YouTubeId");
                OnYouTubeIdChanged();
            }
        }
        private global::System.String _YouTubeId;
        partial void OnYouTubeIdChanging(global::System.String value);
        partial void OnYouTubeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Visibility
        {
            get
            {
                return _Visibility;
            }
            set
            {
                OnVisibilityChanging(value);
                ReportPropertyChanging("Visibility");
                _Visibility = StructuralObject.SetValidValue(value, "Visibility");
                ReportPropertyChanged("Visibility");
                OnVisibilityChanged();
            }
        }
        private Nullable<global::System.Int32> _Visibility;
        partial void OnVisibilityChanging(Nullable<global::System.Int32> value);
        partial void OnVisibilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Catholic
        {
            get
            {
                return _Catholic;
            }
            set
            {
                OnCatholicChanging(value);
                ReportPropertyChanging("Catholic");
                _Catholic = StructuralObject.SetValidValue(value, "Catholic");
                ReportPropertyChanged("Catholic");
                OnCatholicChanged();
            }
        }
        private Nullable<global::System.Boolean> _Catholic;
        partial void OnCatholicChanging(Nullable<global::System.Boolean> value);
        partial void OnCatholicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, true, "Body");
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lawrukmvc.Models", "VideoTag1", "Tag")]
        public EntityCollection<Tag> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tag>("lawrukmvc.Models.VideoTag1", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tag>("lawrukmvc.Models.VideoTag1", "Tag", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
