//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawrukmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Url { get; set; }
        public Nullable<int> BirthdayYear { get; set; }
        public Nullable<int> BirthdayMonth { get; set; }
        public Nullable<int> BirthdayDay { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<long> CellPhone { get; set; }
        public string GoogleId { get; set; }
        public string YahooId { get; set; }
    }
}
