//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawrukmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Body { get; set; }
        public bool Run { get; set; }
        public bool Hike { get; set; }
        public double Distance { get; set; }
        public System.Data.Spatial.DbGeography StartLocation { get; set; }
        public System.Data.Spatial.DbGeography EndLocation { get; set; }
    }
}
